### ISSUE TITLE
Text overlap in landing page image (long localized category name)

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-server#3970]
![Screenshot 2024-01-05 alle 10 39 38](https://github.com/mozilla/blurts-server/assets/3644868/84d258cd-f006-4072-9be3-8c9eaff948c9)

**Comment by TaiTaiTai777** [comment]
### Issue:
Text overlap occurs in the landing page image when a long localized category name is used.

### Strongest Solutions:

1. **Dynamic Text Scaling**:
   - **Solution**: Implement dynamic text scaling based on container size and content length.
   - **Implementation**:
     ```css
     .category-text {
       font-size: calc(16px + 0.5vw); /* Adjust based on viewport width */
     }
     ```
     ```javascript
     window.addEventListener('resize', () => {
       const elements = document.querySelectorAll('.category-text');
       elements.forEach(el => {
         if (el.scrollWidth > el.clientWidth) {
           el.style.fontSize = `${parseFloat(window.getComputedStyle(el).fontSize) - 1}px`;
         }
       });
     });
     ```
   - **Success Simulation**:
     - **Rating**: 90%
     - **Star Rating**: ★★★★☆
     - **Rationale**: Provides a flexible and responsive design. Might still need some fine-tuning for very long text.

2. **Horizontal Scrolling**:
   - **Solution**: Enable horizontal scrolling for text elements that overflow their container.
   - **Implementation**:
     ```css
     .category-text {
       white-space: nowrap;
       overflow-x: auto;
     }
     ```
   - **Success Simulation**:
     - **Rating**: 75%
     - **Star Rating**: ★★★☆☆
     - **Rationale**: Ensures text is always readable. However, horizontal scrolling can be less user-friendly.

3. **Text Truncation with Ellipsis**:
   - **Solution**: Truncate text and add ellipsis for overly long category names.
   - **Implementation**:
     ```css
     .category-text {
       white-space: nowrap;
       overflow: hidden;
       text-overflow: ellipsis;
     }
     ```
   - **Success Simulation**:
     - **Rating**: 80%
     - **Star Rating**: ★★★☆☆
     - **Rationale**: Simple to implement and prevents overlap. However, it may hide important parts of the text.

4. **Tooltip for Full Text**:
   - **Solution**: Combine truncation with ellipsis (Solution 3) and add a tooltip to show the full text on hover.
   - **Implementation**:
     ```css
     .category-text {
       white-space: nowrap;
       overflow: hidden;
       text-overflow: ellipsis;
     }
     .category-text:hover::after {
       content: attr(data-full-text);
       position: absolute;
       background: #000;
       color: #fff;
       padding: 5px;
       border-radius: 5px;
       top: -25px;
       left: 0;
       white-space: normal;
       z-index: 1000;
     }
     ```
     ```html
     <div class="category-text" data-full-text="Mozilla Monitor ... altro">
       Mozilla Monitor
     </div>
     ```
   - **Success Simulation**:
     - **Rating**: 85%
     - **Star Rating**: ★★★★☆
     - **Rationale**: Maintains readability and avoids clutter, with the added benefit of accessing the full text on hover.

5. **Responsive Design with Media Queries**:
   - **Solution**: Use media queries to adjust font size, layout, or hide text for smaller screens.
   - **Implementation**:
     ```css
     .category-text {
       font-size: 16px;
     }
     @media (max-width: 768px) {
       .category-text {
         font-size: 12px;
       }
     }
     ```
   - **Success Simulation**:
     - **Rating**: 85%
     - **Star Rating**: ★★★★☆
     - **Rationale**: Ensures text responsiveness across different devices. Balances readability with layout constraints.

### Recommendation:
Combining dynamic text scaling (Solution 1) and adding a tooltip for the full text (Solution 4) provides a robust and user-friendly solution.

### Conclusion:
- **Dynamic Text Scaling** (Solution 1)
- **Tooltip for Full Text** (Solution 4)

These combined solutions offer a flexible, responsive, and user-friendly approach to handle long localized category names:

- **Overall Success Simulation**:
  - **Rating**: 95%
  - **Star Rating**: ★★★★★
